name: main
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the workflow script
      uses: actions/checkout@main
    - name: Run the Playwright script to capture the screenshot
      run: |
        cd .github/workflows
        npm install
        npx playwright install-deps chromium
        xvfb-run node . ${{secrets.GITHUBCOM_EMAIL}} ${{secrets.GITHUBCOM_PASSWORD}} ${{secrets.GITHUBCOM_SECRET}}
        cd ../..
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add screenshot.png
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Capture the screenshot" -m "This commit was created using GitHub Actions."
        git pull --rebase
        git push
